apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-conversion-webhook
  name: longhorn-conversion-webhook
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    longhorn.io/conversion-webhook: longhorn-conversion-webhook
  ports:
  - name: conversion-webhook
    port: 9501
    targetPort: conversion-wh
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-admission-webhook
  name: longhorn-admission-webhook
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    longhorn.io/admission-webhook: longhorn-admission-webhook
  ports:
  - name: admission-webhook
    port: 9502
    targetPort: admission-wh
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-recovery-backend
  name: longhorn-recovery-backend
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    longhorn.io/recovery-backend: longhorn-recovery-backend
  ports:
  - name: recovery-backend
    port: 9503
    targetPort: recov-backend
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-csi-attacher
  name: longhorn-csi-attacher
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: csi-attacher
  ports:
  - name: csi-attacher
    port: 8000
    targetPort: csi-attacher
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-csi-provisioner
  name: longhorn-csi-provisioner
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: csi-provisioner
  ports:
  - name: csi-provisioner
    port: 8000
    targetPort: csi-provisioner
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-csi-resizer
  name: longhorn-csi-resizer
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: csi-resizer
  ports:
  - name: csi-resizer
    port: 8000
    targetPort: csi-resizer
---
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-csi-snapshotter
  name: longhorn-csi-snapshotter
  namespace: {{ include "release_namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: csi-snapshotter
  ports:
  - name: csi-snapshotter
    port: 8000
    targetPort: csi-snapshotter
