kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  labels:
    app: provisioner-baseimage
  name: baseimage-storageclass
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
  fromBackup: ''
  baseImage: rancher/longhorn-test:baseimage-ext4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: provisioner-baseimage
  name: provisioner-baseimage-service
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: provisioner-baseimage
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: provisioner-baseimage
  name: provisioner-baseimage-statefulset
spec:
  selector:
    matchLabels:
      app: provisioner-baseimage
  serviceName: provisioner-baseimage
  replicas: 2
  template:
    metadata:
      labels:
        app: provisioner-baseimage
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: baseimage-vol
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: baseimage-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: baseimage-storageclass
      resources:
        requests:
          storage: 32Mi
