apiVersion: v1
kind: Pod
metadata:
  labels:
    app: flexvol-baseimage
  name: flexvol-baseimage
  namespace: default
spec:
  containers:
  - name: flexvol-baseimage
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: flexvol
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  volumes:
  - name: flexvol
    flexVolume:
      driver: rancher.io/longhorn
      options:
        size: 32Mi
        numberOfReplicas: "3"
        staleReplicaTimeout: "20"
        fromBackup: ""
        baseImage: rancher/longhorn-test:baseimage-ext4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flexvol-baseimage
  name: flexvol-baseimage
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: flexvol-baseimage
  type: LoadBalancer
