name: Add issues to QA & DevOps project

on:
  pull_request:
    types:
    - labeled

jobs:
  add-to-qa-devops-project:
    name: Add issue to QA & DevOps project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@v0.3.0
      with:
        project-url: https://github.com/orgs/longhorn/projects/4
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labeled: kind/test, area/test-infra
        label-operator: OR
