name: Migrate ZenHub Board to GitHub Project

on:
  workflow_dispatch:
    inputs:
      github_org:
        description: "GitHub organization"
        default: "longhorn"
        required: true
      github_repo:
        description: "GitHub repository"
        default: "longhorn"
        required: true
      github_project:
        description: "GitHub project"
        default: "Longhorn Sprint"
        required: true
permissions:  
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install requests jq

    - name: Migrate ZenHub Board to GitHub Project
      env:
        ZENHUB_TOKEN: ${{ secrets.ZENHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      run: |
        python ./.github/workflows/migrate_zenhub_board_to_github_project.py "${{ inputs.github_org }}" "${{ inputs.github_repo }}" "${{ inputs.github_project }}"
